# Generated by Django 5.0.1 on 2024-02-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='medium', max_length=10)),
                ('crust', models.CharField(choices=[('thin', 'thin'), ('normal', 'normal'), ('thick', 'thick'), ('gluten free', 'gluten free')], default='normal', max_length=15)),
                ('sauce', models.CharField(choices=[('tomato', 'tomato'), ('vegan', 'bbq')], default='tomato', max_length=10)),
                ('cheese', models.CharField(choices=[('mozzarella', 'mozzarella'), ('vegan', 'vegan'), ('low fat', 'low fat')], default='mozzarella', max_length=10)),
                ('toppings', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
