# Generated by Django 5.0.1 on 2024-02-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='desc',
        ),
    ]
