# Generated by Django 3.2.12 on 2024-02-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_pizza_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6)),
            ],
        ),
    ]
