# Generated by Django 3.2.12 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('mozzarella', 'mozzarella'), ('vegan', 'vegan'), ('low fat', 'low fat')], default='mozzarella', max_length=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('thin', 'thin'), ('normal', 'normal'), ('thick', 'thick'), ('gluten free', 'gluten free')], default='normal', max_length=15),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('tomato', 'tomato'), ('vegan', 'bbq')], default='tomato', max_length=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
