# Generated by Django 5.0.1 on 2024-02-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_users'),
        ('templates', '0006_pizza_author'),
    ]

    operations = [
    ]
